Traceback (most recent call last):
  File "/home/josteines/src/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/josteines/src/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/josteines/src/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/josteines/src/.venv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/josteines/src/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/josteines/src/.venv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from fadg.find_and_collocate import SearchCSW
from datetime import datetime

# time_str = '2012-02-21 00:00:00' # Valid time for the datasets I want to access
time_str = '2024-08-07 00:00:00' # Valid time for the datasets this code example uses
time = datetime.strptime(time_str, '%Y-%m-%d %H:%M:%S')#.date()
print(type(time))

# dt = 192
dt = 24
# dt = 10000

# Find all SAR data dt/2 hours back in time from now (if dt and time is not specified):
# sar = SearchCSW(time = time, dt=dt, text="ASAR", endpoint="https://data.csw.met.no/csw")
sar = SearchCSW(text="SAR", endpoint="https://data.csw.met.no/csw") # Worked but got sarwind data (as expected)

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mfadg[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfind_and_collocate[39;00m [38;5;28;01mimport[39;00m SearchCSW
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdatetime[39;00m [38;5;28;01mimport[39;00m datetime
[1;32m      4[0m [38;5;66;03m# time_str = '2012-02-21 00:00:00' # Valid time for the datasets I want to access[39;00m

[0;31mModuleNotFoundError[0m: No module named 'fadg'

